// src/components/Navbar/Navbar.tsx
import pokeballSmallBlue from '../../images/navbar/pokeball-small-blue.png'
import pokemonSmall from '../../images/navbar/pokeball-small.png'
import pokeballDefault from '../../images/navbar/default.png'
import './Navbar.css'

export default function Navbar() {
  return (
    <div className="navbar flex w-full">
      <div className="details flex justify-start items-center">
        <div className="deco flex w-2.5 h-2.5 m-2.5 justify-self-start self-end" />
        <div className="title flex justify-between items-center m-auto w-2/5 p-0.5">
          <img src={pokeballSmallBlue} />
          <span><h3>Pokédex</h3></span>
          <img src={pokeballSmallBlue} />
        </div>
        <div className="capture-details flex justify-center self-center w-2/5">
          <span className="caught flex justify-between items-center w-full" id="totalCaught">
            <img src={pokemonSmall} />
            <p>898</p>
          </span>
          <span className="caught flex justify-between items-center w-full" id="totalPokemon">
            <img src={pokeballDefault} />
            <p>898</p>
          </span>
        </div>
      </div>
      <div className="sortby flex justify-center items-center w-1/3">
        <div className="container flex justify-center self-center text-center w-4/5 h-1/2">
          <p className="m-auto">By Number</p>
        </div>
      </div>
      <div className="nav-deco flex justify-self-end self-end h-full">
        <div className="fill1" />
        <div className="fill2" />
        <div className="fill3" />
      </div>
    </div>
  )
}

// src/components/Navigation/Navbar.vue
<script setup>
</script>
<template>
  <div class="navbar">
    <div class="details">
      <div class="deco" />
      <div class="title">
        <img src="../../assets/navbar/pokeball-small-blue.png" />
        <span>Pokédex</span>
        <img src="../../assets/navbar/pokeball-small-blue.png" />
      </div>
      <div class="capture-details">
        <span class="caught" id="totalCaught">
          <img src="../../assets/navbar/pokeball-small.png" />
          <p>898</p>
        </span>
        <span class="caught" id="totalPokemon">
          <img src="../../assets/navbar/default.png" />
          <p>898</p>
        </span>
      </div>
    </div>
    <div class="sortby">
      <div class="container">
        <p>By Number</p>
      </div>
    </div>
    <div class="nav-deco">
      <div class="fill1" />
      <div class="fill2" />
      <div class="fill3" />
    </div>
  </div>
</template>

<style lang="scss" scoped>
.navbar {
  display: flex;
  width: 100%;
  background: #5b80f5;
  border-bottom: 5px solid #3a403d;
  height: 70px;
}
.deco {
  display: flex;
  width: 10px;
  height: 10px;
  background: #2e4b92;
  margin: 10px;
  justify-self: flex-start;
  align-self: flex-end;
}
.details {
  width: 70%;
  display: flex;
  justify-content: flex-start;
  align-items: center;
}
.title {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 5%;
  width: 40%;
  background: #88daf2;
  border: 5px solid #3353a8;
  border-radius: 30px;
  padding: 2px;

  img {
    width: 30px;
    height: 30px;
  }

  p {
    margin: 0;
  }
}
.capture-details {
  display: flex;
  justify-content: center;
  align-self: center;
  width: 40%;

  .caught {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin: 5%;
    padding: 3px;
    width: 100%;
    background: #1b2d77;
    border-radius: 20px;

    img {
      margin: 0;
      width: 23px;
      height: 23px;
    }

    p {
      margin: 0 5px 0 0;
    }
  }
}
.sortby {
  display: flex;
  justify-content: center;
  align-items: center;
  background: #71a4f3;
  width: 30%;

  p {
    margin: 0;
  }

  .container {
    display: flex;
    justify-content: center;
    align-self: center;
    width: 80%;
    height: 50%;
    background: #4379cf;
    border-radius: 50px;
  }
}

.nav-deco {
  display: flex;
  justify-self: flex-end;
  align-self: flex-end;
  height: 100%;
  .fill1 {
    width: 10px;
    height: 100%;
    background: #79a9e9;
  }
  .fill2 {
    width: 10px;
    height: 100%;
    background: #8cbfee;
  }
  .fill3 {
    width: 5px;
    height: 100%;
    background: #abdefb;
  }
}
</style>
